import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Board from "../components/Board/Board";
import Hand from "../components/Hand/Hand";
import GameStatus from "../components/GameStatus/GameStatus";
import { useRouter } from "next/router";
import { useEngine } from "../engine/store";
import { useEffect, useState } from "react";
import { EngineState } from "../engine/types";

const getHasGame = ({ playerTurnsOrder }: EngineState) =>
  playerTurnsOrder.length;

const getResetGame = ({ resetGame }: EngineState) => resetGame;

const getPhase = ({ gamePhase }: EngineState) => gamePhase;

const Home: NextPage = () => {
  const [isMounted, setIsMounted] = useState(false);
  const router = useRouter();
  const hasGame = useEngine(getHasGame);
  const resetGame = useEngine(getResetGame);
  const phase = useEngine(getPhase);

  useEffect(() => {
    if (!hasGame) {
      router.replace("/");
    }
  }, [hasGame, router]);
  useEffect(() => {
    setIsMounted(true);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Tsuro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Tsuro</h1>
        {isMounted && (
          <>
            <GameStatus />
            <Board />
            {phase === "joining" && (
              <button onClick={resetGame}>Start game</button>
            )}
            {phase === "main" && <Hand />}
            {phase === "finished" && (
              <button onClick={resetGame}>New game</button>
            )}
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
