import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Board from "../components/Board/Board";
import Hand from "../components/Hand/Hand";
import GameStatus from "../components/GameStatus/GameStatus";
import { useRouter } from "next/router";
import { useEngine } from "../engine/store";
import { useEffect, useState } from "react";
import { EngineState } from "../engine/types";
import { useNetwork } from "../engine/network";

const getHasGame = ({ isConnected, isLoading }: EngineState) =>
  isConnected || isLoading;

const Home: NextPage = () => {
  const [isMounted, setIsMounted] = useState(false);
  const router = useRouter();
  const hasGame = useEngine(getHasGame);

  useNetwork();

  useEffect(() => {
    if (!hasGame && isMounted) {
      router.replace("/");
    }
  }, [hasGame, router, isMounted]);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Tsuro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Tsuro</h1>
        {/* Prevent game from pre-rendering on server as rehydration will fail because of session storage state */}
        {isMounted && (
          <>
            <GameStatus />
            <Board />
            <Hand />
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
